title: Project Pilot
baseurl: ""
url: https://project-pilot-coding.github.io
email: project-pilot-coding@gmail.com
github_username: project-pilot-coding

permalink: /:slug

defaults:
  - 
    scope:
      path: ""
    values:
      layout: default
      title: Learn to Code through Projects
  -
    scope:
      type: posts
    values:
      permalink: /:slugified_categories/:slug

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-redirect-from
